/* eslint-disable */
module.exports= [
    {
    "parts":[{
        "partId":"1",
        "partName":"头部",
        "extraMap":{}
    },
        {
        "partId":"2",
        "partName":"眼部",
        "extraMap":{}
    },
        {
        "partId":"3",
        "partName":"鼻部",
        "extraMap":{}
    },
        {
        "partId":"4",
        "partName":"口腔",
        "extraMap":{}
    },
        {
        "partId":"5",
        "partName":"耳部",
        "extraMap":{}
    },
        {
        "partId":"6",
        "partName":"面部",
        "extraMap":{}
    },
        {
        "partId":"7",
        "partName":"颈部",
        "extraMap":{}
    },
        {
        "partId":"8",
        "partName":"上肢",
        "extraMap":{}
    },
        {
        "partId":"9",
        "partName":"手部",
        "extraMap":{}
    },
        {
        "partId":"10",
        "partName":"胸部",
        "extraMap":{}
    },{
        "partId":"11",
        "partName":"腹部",
        "extraMap":{}
    },{
        "partId":"12",
        "partName":"背部",
        "extraMap":{}
    },{
        "partId":"13",
        "partName":"腰部",
        "extraMap":{}
    },{
        "partId":"14",
        "partName":"臀部",
        "extraMap":{}
    },{
        "partId":"15",
        "partName":"生殖部位",
        "extraMap":{}
    },{
        "partId":"16",
        "partName":"腿部",
        "extraMap":{}
    },{
        "partId":"17",
        "partName":"足部",
        "extraMap":{}
    },{
        "partId":"18",
        "partName":"血液",
        "extraMap":{}
    },{
        "partId":"19",
        "partName":"精神",
        "extraMap":{}
    },{
        "partId":"20",
        "partName":"皮肤",
        "extraMap":{}
    },{
        "partId":"21",
        "partName":"其他",
        "extraMap":{}
    }],
    "groupsId":"1",
    "groupsName":"男",
    "extraMap":{}
},
    {
    "parts":[{
        "partId":"1",
        "partName":"头部",
        "extraMap":{}
    },{
        "partId":"2",
        "partName":"眼部",
        "extraMap":{}
    },{
        "partId":"3",
        "partName":"鼻部",
        "extraMap":{}
    },{
        "partId":"4",
        "partName":"口腔",
        "extraMap":{}
    },{
        "partId":"5",
        "partName":"耳部",
        "extraMap":{}
    },{
        "partId":"6",
        "partName":"面部",
        "extraMap":{}
    },{
        "partId":"7",
        "partName":"颈部",
        "extraMap":{}
    },{
        "partId":"8",
        "partName":"上肢",
        "extraMap":{}
    },{
        "partId":"9",
        "partName":"手部",
        "extraMap":{}
    },{
        "partId":"10",
        "partName":"胸部",
        "extraMap":{}
    },{
        "partId":"11",
        "partName":"腹部",
        "extraMap":{}
    },{
        "partId":"12",
        "partName":"背部",
        "extraMap":{}
    },{
        "partId":"13",
        "partName":"腰部",
        "extraMap":{}
    },{
        "partId":"14",
        "partName":"臀部",
        "extraMap":{}
    },{
        "partId":"15",
        "partName":"生殖部位",
        "extraMap":{}
    },{
        "partId":"16",
        "partName":"腿部",
        "extraMap":{}
    },{
        "partId":"17",
        "partName":"足部",
        "extraMap":{}
    },{
        "partId":"18",
        "partName":"血液",
        "extraMap":{}
    },{
        "partId":"19",
        "partName":"精神",
        "extraMap":{}
    },{
        "partId":"20",
        "partName":"皮肤",
        "extraMap":{}
    },{
        "partId":"21",
        "partName":"其他",
        "extraMap":{}
    }],
    "groupsId":"2",
    "groupsName":"女",
    "extraMap":{}
},
    {
    "parts":[{
        "partId":"1",
        "partName":"头部",
        "extraMap":{}
    },{
        "partId":"2",
        "partName":"眼部",
        "extraMap":{}
    },{
        "partId":"3",
        "partName":"鼻部",
        "extraMap":{}
    },{
        "partId":"4",
        "partName":"口腔",
        "extraMap":{}
    },{
        "partId":"5",
        "partName":"耳部",
        "extraMap":{}
    },{
        "partId":"6",
        "partName":"面部",
        "extraMap":{}
    },{
        "partId":"7",
        "partName":"颈部",
        "extraMap":{}
    },{
        "partId":"8",
        "partName":"上肢",
        "extraMap":{}
    },{
        "partId":"9",
        "partName":"手部",
        "extraMap":{}
    },{
        "partId":"10",
        "partName":"胸部",
        "extraMap":{}
    },{
        "partId":"11",
        "partName":"腹部",
        "extraMap":{}
    },{
        "partId":"12",
        "partName":"背部",
        "extraMap":{}
    },{
        "partId":"13",
        "partName":"腰部",
        "extraMap":{}
    },{
        "partId":"14",
        "partName":"臀部",
        "extraMap":{}
    },{
        "partId":"15",
        "partName":"生殖部位",
        "extraMap":{}
    },{
        "partId":"16",
        "partName":"腿部",
        "extraMap":{}
    },{
        "partId":"17",
        "partName":"足部",
        "extraMap":{}
    },{
        "partId":"18",
        "partName":"血液",
        "extraMap":{}
    },{
        "partId":"19",
        "partName":"精神",
        "extraMap":{}
    },{
        "partId":"20",
        "partName":"皮肤",
        "extraMap":{}
    },{
        "partId":"21",
        "partName":"其他",
        "extraMap":{}
    }],
    "groupsId":"3",
    "groupsName":"儿童",
    "extraMap":{}
}
]
